"""Add ArticleImage model for multiple images per article

Revision ID: 0761fa5d6757
Revises: cec0286ec2ba
Create Date: 2025-09-18 22:29:08.579855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0761fa5d6757'
down_revision: Union[str, Sequence[str], None] = 'cec0286ec2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('article_id', sa.Integer(), nullable=False),
                    sa.Column('image_path', sa.String(
                        length=500), nullable=False),
                    sa.Column('caption', sa.String(length=200), nullable=True),
                    sa.Column('display_order', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_article_images_id'),
                    'article_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_images_id'), table_name='article_images')
    op.drop_table('article_images')
    # ### end Alembic commands ###
