"""Redesign Cat model for kittens: replace role/breed/vaccination with gender/litter_code/date_of_birth

Revision ID: 3da59699d7a0
Revises: a5c02bea60eb
Create Date: 2025-10-11 23:22:23.174534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da59699d7a0'
down_revision: Union[str, Sequence[str], None] = 'a5c02bea60eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new columns with default values to handle existing data
    op.add_column('cats', sa.Column('gender', sa.String(
        length=10), nullable=False, server_default='unknown'))
    op.add_column('cats', sa.Column('litter_code', sa.String(
        length=20), nullable=False, server_default='L000'))
    op.add_column('cats', sa.Column('date_of_birth', sa.Date(),
                  nullable=False, server_default='2024-01-01'))
    op.add_column('cats', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('cats', sa.Column('is_available', sa.Boolean(),
                  nullable=True, server_default='1'))

    # Update existing records with meaningful data based on their names/positions
    op.execute("UPDATE cats SET gender = 'female' WHERE id % 2 = 0")
    op.execute("UPDATE cats SET gender = 'male' WHERE id % 2 = 1")
    op.execute("UPDATE cats SET litter_code = 'L' || SUBSTR('000' || id, -3)")
    op.execute(
        "UPDATE cats SET date_of_birth = DATE('2024-01-01', '+' || (id * 30) || ' days')")
    op.execute("UPDATE cats SET description = 'Migrated from previous cat profile: ' || COALESCE(bio, 'No description available')")
    op.execute("UPDATE cats SET is_available = 1")

    # Create unique constraint on litter_code
    op.create_unique_constraint(None, 'cats', ['litter_code'])

    # Drop old columns
    op.drop_column('cats', 'breed')
    op.drop_column('cats', 'award')
    op.drop_column('cats', 'rabies_vaccinated')
    op.drop_column('cats', 'bio')
    op.drop_column('cats', 'role')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column(
        'role', sa.VARCHAR(length=20), nullable=False))
    op.add_column('cats', sa.Column('bio', sa.TEXT(), nullable=True))
    op.add_column('cats', sa.Column(
        'rabies_vaccinated', sa.BOOLEAN(), nullable=True))
    op.add_column('cats', sa.Column(
        'award', sa.VARCHAR(length=200), nullable=True))
    op.add_column('cats', sa.Column(
        'breed', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'cats', type_='unique')
    op.drop_column('cats', 'is_available')
    op.drop_column('cats', 'description')
    op.drop_column('cats', 'date_of_birth')
    op.drop_column('cats', 'litter_code')
    op.drop_column('cats', 'gender')
    # ### end Alembic commands ###
