"""Add base64 image fields to cats, articles, and article_images tables

Revision ID: a5c02bea60eb
Revises: 3403d5782880
Create Date: 2025-09-21 18:32:45.372218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c02bea60eb'
down_revision: Union[str, Sequence[str], None] = '3403d5782880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_images', sa.Column('image_base64', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('featured_image_base64', sa.Text(), nullable=True))
    op.add_column('cats', sa.Column('photo_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cats', 'photo_base64')
    op.drop_column('articles', 'featured_image_base64')
    op.drop_column('article_images', 'image_base64')
    # ### end Alembic commands ###
